//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;

[assembly: AssemblyTitle("Cake.Kudu")]
[assembly: AssemblyDescription("Cake Kudu AddIn")]
[assembly: AssemblyCompany("WCOM AB")]
[assembly: AssemblyProduct("Cake.Kudu")]
[assembly: AssemblyVersion("0.11.0.0")]
[assembly: AssemblyFileVersion("0.11.0.0")]
[assembly: AssemblyInformationalVersion("0.11.0-beta.1+0.Branch.release/0.11.0.Sha.c2c7f1f4d753a50aea2490d6ec338bfd95a6aae1")]
[assembly: AssemblyCopyright("Copyright © WCOM AB 2017")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

